feat: sign in validation
sabrina34352/task-rep pull request #17
Opened 2022-06-14 19:24 UTC by sabrina34352

THIS PROJECT IS IN DEVELOPMENT MODE.

### added validation for sign in page

## Description
Создать кастомный инпут компонент. Заменить инпуты на странице “Sign in” новым кастомным инпутом. На странице “Sign in” у инпутов должна быть валидация: Username должен быть только email (пример: dawdavfa@qwe.ru и т.д.), поле обязательно Password минимальная длинна 8 символов, должен включать хоть 1 цифру и 1 букву, поле обязательно Если валидация не прошла, кнопка “Войти” должна быть disabled.

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/63979168/173671647-39ef793e-022f-41a7-b990-eb8f76465a79.png)
### if successful: 
![image](https://user-images.githubusercontent.com/63979168/173671822-689892f9-d066-4e6a-8bf6-3d596aadc9f2.png)
### if not successful: 
![image](https://user-images.githubusercontent.com/63979168/173671888-f8c91a37-40b6-4569-8ddb-f28261ae4742.png)

2022-06-20 06:22 UTC, vshynkarova requested changes
After press "sign in" should be redirect to the main page

2022-06-20 06:22 UTC, vshynkarova commented on src/App.js
> +                    <Route path="*" element={<NotFoundPage />} />
If i'm not mistaking, you don't need to have a path with * for NotFoundPage

2022-06-20 06:22 UTC, vshynkarova commented on src/components/SignIn/index.jsx
> +    const [errorMessage, setErrorMessage] = useState('')
Is it possible not to store this values here, but check it inside `Input` component?

2022-07-01 07:32 UTC, vshynkarova approved these changes

2022-07-12 13:20 UTC, sabrina34352 commented on src/App.js
> +                    <Route path="*" element={<NotFoundPage />} />
The version that i use requires it, and i couldn't find any alternatives

2022-07-12 13:20 UTC, merged