Dynamic pages
sabrina34352/task-rep pull request #21
Opened 2022-07-16 13:47 UTC by sabrina34352

THIS PROJECT IS IN DEVELOPMENT MODE.

card/:id added

## Description
Добавить новую страницу “/card/:id” При открытии страницы “/card/:id” на странице должен отобразится заголовок карточки, её текст и возможность редактировать заголовок и текст. При двойном клике на карточку в режиме, когда карточка в режиме просмотра (не редактировании), пользователь должен перейти на страницу “/card/:id

## Context

## Screenshots (if appropriate):

2022-07-21 06:19 UTC, vshynkarova requested changes
This pull request looks much better than the first one, well done!

To fix: 
1. after login I want to be redirected to the main page.

2. I don't want to see placeholders in not edit mode.

<img width="537" alt="Screenshot 2022-07-21 at 08 47 24" src="https://user-images.githubusercontent.com/96103612/180142705-0c15b85e-96b9-4630-9ab3-b586e033976d.png">


3. Set the check mark or update style. 

https://user-images.githubusercontent.com/96103612/180143000-ef895a3b-e54f-4066-b9de-115c9ade1057.mov

2022-07-21 06:19 UTC, vshynkarova commented on src/App.js
> +  }, [])
Why you did this dispatch in this component?

2022-07-21 06:19 UTC, vshynkarova commented on .prettierrc.json
> +  "semi": false,
Update to `semi: true`

2022-07-21 06:19 UTC, vshynkarova commented on src/components/Card/index.jsx
> +  const handleDOubleClick = () => {
Typo: handleDoubleClick

2022-07-21 06:19 UTC, vshynkarova commented on src/components/Card/index.jsx
> +          id: uuidv4(),
Same names can be omitted: 
`{
          body,
          header,
          id: uuidv4()
 }`

2022-07-21 06:19 UTC, vshynkarova commented on src/components/Card/index.jsx
>  export default CardWithLoadingDelay
No need to fix, just for information: More sommon way to use export: `export default withLoadingDelay(Card)`.

2022-07-21 06:19 UTC, vshynkarova commented on src/components/CardList/index.jsx
> +          cards.cards
`cards.cards`?))) Rename!!

2022-07-21 06:19 UTC, vshynkarova commented on src/components/DataFetching/index.js
> +import axios from 'axios'
Move this file in the `api` folder. 
Leave only ` axios.get`.
You don't need here `then` and `catch`.

2022-07-21 06:19 UTC, vshynkarova commented on src/components/Input/index.jsx
>  import PropTypes from 'prop-types'
Remove unused imports from this file

2022-07-21 06:19 UTC, vshynkarova commented on src/components/Input/index.jsx
> +  width: 20rem;
Move styled component in `styles` file and import from there

2022-07-21 06:19 UTC, vshynkarova commented on src/components/SignIn/index.jsx
>    `}
Move styled components in styles file and import from there

2022-07-21 06:19 UTC, vshynkarova commented on src/components/SignIn/index.jsx
> +  const [errorMessage, setErrorMessage] = useState('')
Do you really need both of them?
`errorExist` is redundant.

2022-07-21 06:19 UTC, vshynkarova commented on src/store/AllCardsSlice/index.js
> +    },
Praise: you did what I mentioned. Great!

Now let's think: you have state statuses, how can you use this in your application?

2022-07-22 08:37 UTC, sabrinababakulova commented on src/App.js
> +  }, [])
because otherwise the cards are not being loaded into store

2022-07-25 08:06 UTC, vshynkarova commented on src/components/CardList/index.jsx
> +  if (allCardsInfo.status === 'loading') {
❤️

2022-07-26 07:34 UTC, vshynkarova approved these changes

2022-07-26 07:56 UTC, merged