read only button, multiple cards added
sabrina34352/task-rep pull request #4
Opened 2022-05-20 08:28 UTC by sabrina34352

THIS PROJECT IS IN DEVELOPMENT MODE.

### added ReadOnly button, that disables the possible changes to cards, and also there are multiple cards now

## Description

## Context

## Screenshots (if appropriate):

2022-05-20 09:24 UTC, vshynkarova requested changes
1. You shouldn't move Card component to the different file. For collection create new component - CardList. 
2. Mock cards data with `json` file.

2022-05-20 10:18 UTC, sabrina34352 commented
![image](https://user-images.githubusercontent.com/63979168/169507570-6a6b24de-3bc5-4bff-a9a6-2407a84a94e3.png)
## data is from json file, provided to CardList and Card as a props

2022-05-20 10:29 UTC, vshynkarova requested changes

2022-05-20 10:29 UTC, vshynkarova commented on src/Components/CardList/index.jsx
> +function CardList({ props }) {
Add more sensible name

2022-05-20 10:29 UTC, vshynkarova commented on src/Components/CardList/index.jsx
> +                ))}
Don't use index like a key.

2022-05-20 10:29 UTC, vshynkarova commented on src/Data/CardData.json
> +[
Praise: good job

2022-05-20 10:31 UTC, vshynkarova commented on src/Components/CardList/index.jsx
> +function CardList({ props }) {
Use arrow expressions for functional components

2022-05-20 13:22 UTC, vshynkarova approved these changes
Looks more attractive now)

2022-05-20 13:22 UTC, vshynkarova commented on src/Components/CardList/index.jsx
> +const CardList = ({ CardData }) => {
`CardData` shouldn't have first capital letter

2022-05-20 13:22 UTC, vshynkarova commented on src/Components/Card/index.jsx
> +    const [body, setBody] = useState(props.data.Body)
`Header` and `Body` shouldn't have first capital letter

2022-05-20 13:22 UTC, vshynkarova commented on src/Components/Card/index.jsx
> +const Card = (props) => {
use destructuring props

2022-05-20 13:22 UTC, vshynkarova commented on src/Components/Card/index.jsx
> +    function validationOnDiscard() {
For function you also can use arrow notation)

2022-05-23 07:35 UTC, vshynkarova commented
You can merge this branch into main.

2022-05-23 07:46 UTC, merged